# Generated by Django 4.0.4 on 2022-05-19 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.rank', verbose_name='Ранг'),
        ),
    ]
