# Generated by Django 4.0.4 on 2022-05-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rank",
            name="experience_required",
            field=models.IntegerField(verbose_name="Необходимый опыт"),
        ),
    ]
