# Generated by Django 4.0.4 on 2022-05-22 18:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_rank_experience_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True, default=None, image_field=None, max_length=18, null=True, samples=None
            ),
        ),
    ]
