# Generated by Django 4.0.4 on 2022-05-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rank_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="actorprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/", verbose_name="Изображение"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/", verbose_name="Изображение"),
        ),
    ]
