# Generated by Django 4.0.4 on 2022-05-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_actorprofile_image_userprofile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="actorprofile",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]
