# Generated by Django 4.0.4 on 2022-05-11 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactsGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="ContactType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=100)),
                (
                    "contacts_group_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.contactsgroup"),
                ),
                ("type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.contacttype")),
            ],
        ),
    ]
