# Generated by Django 4.0.4 on 2022-05-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contacts_group_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="core.contactsgroup",
                verbose_name="Группа контактов",
            ),
        ),
    ]
