# Generated by Django 4.0.4 on 2022-05-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_city_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="contacts_group_id",
            new_name="contacts_group",
        ),
    ]
