# Generated by Django 4.0.4 on 2022-05-11 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("users", "0001_initial"),
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.CharField(max_length=250, verbose_name="Адрес")),
                ("fias", models.CharField(max_length=50, verbose_name="ФИАС")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="theatres.city", verbose_name="Город"
                    ),
                ),
            ],
            options={
                "verbose_name": "Местоположение",
                "verbose_name_plural": "Местоположения",
            },
        ),
        migrations.CreateModel(
            name="Troupe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Труппа",
                "verbose_name_plural": "Труппы",
            },
        ),
        migrations.CreateModel(
            name="TroupeMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(blank=True, max_length=100, null=True, verbose_name="Роль")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.actorprofile", verbose_name="Профиль"
                    ),
                ),
                (
                    "troupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="theatres.troupe", verbose_name="Труппа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник труппы",
                "verbose_name_plural": "Участники трупп",
            },
        ),
        migrations.CreateModel(
            name="Theatre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "contacts",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.contactsgroup",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="theatres.location",
                        verbose_name="Местоположение",
                    ),
                ),
                (
                    "reviews",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rating.reviewgroup",
                        verbose_name="Отзывы",
                    ),
                ),
                (
                    "troupe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="theatres.troupe",
                        verbose_name="Труппа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Театр",
                "verbose_name_plural": "Театры",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "reviews",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rating.reviewgroup",
                        verbose_name="Отзывы",
                    ),
                ),
                (
                    "theatre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="theatres.theatre", verbose_name="Театр"
                    ),
                ),
                (
                    "troupe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="theatres.troupe",
                        verbose_name="Труппа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
    ]
