# Generated by Django 4.0.4 on 2022-05-15 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatres", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="troupemember",
            name="troupe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="theatres.troupe",
                verbose_name="Труппа",
            ),
        ),
    ]
