# Generated by Django 4.0.4 on 2022-05-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatres", "0003_alter_event_theatre"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="theatre",
            name="description",
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name="Описание"),
        ),
    ]
