# Generated by Django 4.0.4 on 2022-05-19 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("theatres", "0004_event_description_theatre_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="troupemember",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="troupe_members",
                to="users.actorprofile",
                verbose_name="Профиль",
            ),
        ),
    ]
