# Generated by Django 4.0.4 on 2022-05-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatres", "0005_alter_troupemember_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
        migrations.AddField(
            model_name="theatre",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]
