# Generated by Django 4.0.4 on 2022-05-24 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_city_location"),
        ("theatres", "0007_moderationevent_moderationtheatre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="city",
        ),
        migrations.AlterField(
            model_name="theatre",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.location", verbose_name="Местоположение"
            ),
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
