# Generated by Django 4.0.4 on 2022-05-12 04:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("theatres", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meetup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start", models.DateTimeField(verbose_name="Время встречи")),
                (
                    "participants_limit",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимальное кол-во участников",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=2500, null=True, verbose_name="Описание")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="theatres.event", verbose_name="Событие"
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Организатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Встреча",
                "verbose_name_plural": "Встречи",
            },
        ),
        migrations.CreateModel(
            name="MeetupParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "meetup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="group.meetup", verbose_name="Встреча"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник встречи",
                "verbose_name_plural": "Участники встреч",
            },
        ),
    ]
