# Generated by Django 4.0.4 on 2022-05-15 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupparticipant",
            name="meetup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="group.meetup",
                verbose_name="Встреча",
            ),
        ),
    ]
