# Generated by Django 4.0.4 on 2022-05-19 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatres", "0003_alter_event_theatre"),
        ("group", "0002_alter_meetupparticipant_meetup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetup",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetups",
                to="theatres.event",
                verbose_name="Событие",
            ),
        ),
    ]
