# Generated by Django 4.0.4 on 2022-05-19 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("group", "0003_alter_meetup_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetup",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Организатор",
            ),
        ),
    ]
