# Generated by Django 4.0.4 on 2022-05-11 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("star", models.IntegerField(validators=[core.validators.RangeValidator(1, 5)], verbose_name="Оценка")),
                ("content", models.CharField(blank=True, max_length=2500, null=True, verbose_name="Содержание")),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.CreateModel(
            name="ReviewCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Категория отзыва",
                "verbose_name_plural": "Категории отзывов",
            },
        ),
        migrations.CreateModel(
            name="ReviewGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Группа отзывов",
                "verbose_name_plural": "Группы отзывов",
            },
        ),
        migrations.CreateModel(
            name="ReviewRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("star", models.BooleanField(verbose_name="Оценка")),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="rating.review",
                        verbose_name="Отзыв",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка отзыва",
                "verbose_name_plural": "Оценки отзывов",
            },
        ),
        migrations.AddField(
            model_name="review",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rating.reviewcategory", verbose_name="Категория"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="review_group_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rating.reviewgroup", verbose_name="Группа отзывов"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Пользователь"
            ),
        ),
    ]
